# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 5b8f02649e2dd9046620a618e129a483b417bf9157b399ff02d2da244fc67e382b5045f9b9010fb19d81443f000dd49c64eb5a1dcb2154d33b3e44e69c557ec9

test:
  secret_key_base: c634a3be5087c8d08359888ea70ca9547c1cc9e8f2156aacbdb24bcb12516ba8e85948995f9553ff98185db121c92e8a2f1bb756de8f32805bd4697958391eb6

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
